=== Wollac/ubahn/transport.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="transport">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="stations" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="station" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="lines" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="line" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="stations" minOccurs="1" maxOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="station" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required"/>
                              <xs:attribute name="time" type="xs:integer" use="required"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Wollac/ubahn/instances/simple.xml
<?xml version="1.0" encoding="UTF-8"?>

<transport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="transport.xsd">

  <stations>
    <station name="A"/>
    <station name="B"/>
  </stations>

  <lines>
    <line name="U1">
      <stations>
        <station name="A" time="0"/>
        <station name="B" time="1"/>
      </stations>
    </line>
  </lines>

</transport>
